hsp_adaptive:
    policy_config_path: random1/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    train: True
mep1_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep1_init_actor.pt
mep1_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep1_mid_actor.pt
mep1_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep1_final_actor.pt
mep2_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep2_init_actor.pt
mep2_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep2_mid_actor.pt
mep2_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep2_final_actor.pt
mep3_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep3_init_actor.pt
mep3_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep3_mid_actor.pt
mep3_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep3_final_actor.pt
mep4_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep4_init_actor.pt
mep4_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep4_mid_actor.pt
mep4_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep4_final_actor.pt
mep5_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep5_init_actor.pt
mep5_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep5_mid_actor.pt
mep5_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep5_final_actor.pt
mep6_1:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep6_init_actor.pt
mep6_2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep6_mid_actor.pt
mep6_3:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/mep/s1/mep6_final_actor.pt
hsp2:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp2_w0_actor.pt
hsp4:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp4_w0_actor.pt
hsp5:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp5_w0_actor.pt
hsp7:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp7_w0_actor.pt
hsp13:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp13_w0_actor.pt
hsp15:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp15_w0_actor.pt
hsp17:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp17_w0_actor.pt
hsp19:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp19_w0_actor.pt
hsp20:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp20_w0_actor.pt
hsp21:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp21_w0_actor.pt
hsp22:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp22_w0_actor.pt
hsp24:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp24_w0_actor.pt
hsp27:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp27_w0_actor.pt
hsp28:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp28_w0_actor.pt
hsp29:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp29_w0_actor.pt
hsp30:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp30_w0_actor.pt
hsp32:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp32_w0_actor.pt
hsp35:
    policy_config_path: random1/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random1/hsp/s1/hsp35_w0_actor.pt
