hsp_adaptive:
    policy_config_path: unident_s/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    train: True
mep1_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep1_init_actor.pt
mep1_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep1_mid_actor.pt
mep1_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep1_final_actor.pt
mep2_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep2_init_actor.pt
mep2_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep2_mid_actor.pt
mep2_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep2_final_actor.pt
mep3_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep3_init_actor.pt
mep3_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep3_mid_actor.pt
mep3_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep3_final_actor.pt
mep4_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep4_init_actor.pt
mep4_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep4_mid_actor.pt
mep4_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep4_final_actor.pt
mep5_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep5_init_actor.pt
mep5_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep5_mid_actor.pt
mep5_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep5_final_actor.pt
mep6_1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep6_init_actor.pt
mep6_2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep6_mid_actor.pt
mep6_3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/mep/s1/mep6_final_actor.pt
hsp1:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp1_w0_actor.pt
hsp2:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp2_w0_actor.pt
hsp3:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp3_w0_actor.pt
hsp5:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp5_w0_actor.pt
hsp7:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp7_w0_actor.pt
hsp9:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp9_w0_actor.pt
hsp11:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp11_w0_actor.pt
hsp13:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp13_w0_actor.pt
hsp15:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp15_w0_actor.pt
hsp16:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp16_w0_actor.pt
hsp22:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp22_w0_actor.pt
hsp27:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp27_w0_actor.pt
hsp28:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp28_w0_actor.pt
hsp31:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp31_w0_actor.pt
hsp32:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp32_w0_actor.pt
hsp33:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp33_w0_actor.pt
hsp34:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp34_w0_actor.pt
hsp35:
    policy_config_path: unident_s/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: unident_s/hsp/s1/hsp35_w0_actor.pt
